name: stellar
channels:
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.8    # Python version 3.8
  - compilers
  - llvm-openmp
  - sphinx
  - importlib_resources
  - pip           # Python package
  - pandas        # Labeled array library
  - netCDF4       # Wrapper for netcdf4
  - xarray        # N-d labeled array library
  - matplotlib    # 2D plotting library
  - numpy         # N-d array and numerics
  - numpy-indexed # Numerics adds on
  - scipy         # Common math/stats/science functions
  - scikit-image  # Image processing routines
  - scikit-learn  # Machine learning library
  - scikit-fuzzy  # Fuzzy logic library
  - geopandas     # Labeled array library for geosciences
  - shapely       # Geometric library
  - cftime        # Time units decoder
  - cartopy       # Geographic plotting toolkit
  - myst-nb       # Notebook syntax
  - sympy         # Symbolic expression
  - cmocean       # Colormaps for oceanography
  - jupyterlab    # Jupyter Lab environment
  - jupyter-book  # Jupyter book environment
  - basemap       # Mapping package
  - h5py          # Wrapper for HDF5
  - pymannkendall # Mann-Kendall trend analysis
  - seaborn       # Statistical visualizations
  - pyresample    # Geographic resampling tools
  - petsc4py
  - meshio
  - vtk
  - pre-commit
  - ruamel.yaml
  - mpi4py
  - cython
  - pooch
  - ipywidgets
  - itkwidgets
  - ipyvtklink
  - ipyevents
  - nodejs
  - pyvista
  - pyevtk
  - panel
  - gdown
  - jigsawpy
  - pysheds
  - rioxarray
  - rasterio
  - ipygany
  - fiona
  - pycrs
  - richdem
  - holoviews
  - geoviews
  - hvplot
  - panel
  - wget
  - basemap-data-hires
  - pip:
    - pyproj      # Geographic projections
    - jupyter-book==0.10.1
    - fastfunc
    - meshplex
    - gospl==0.2.5
    - stripy
    - zmapio
